INSERT INTO public.city (state_id ,city_name,capital) VALUES
	 (1,'Maroa',false),
	 (1,'Puerto Ayacucho',true),
	 (1,'San Fernando de Atabapo',false),
	 (2,'Anaco',false),
	 (2,'Aragua de Barcelona',false),
	 (2,'Barcelona',true),
	 (2,'Boca de Uchire',false),
	 (2,'Cantaura',false),
	 (2,'Clarines',false),
	 (2,'El Chaparro',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (2,'El Pao Anzoátegui',false),
	 (2,'El Tigre',false),
	 (2,'El Tigrito',false),
	 (2,'Guanape',false),
	 (2,'Guanta',false),
	 (2,'Lechería',false),
	 (2,'Onoto',false),
	 (2,'Pariaguán',false),
	 (2,'Píritu',false),
	 (2,'Puerto La Cruz',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (2,'Puerto Píritu',false),
	 (2,'Sabana de Uchire',false),
	 (2,'San Mateo Anzoátegui',false),
	 (2,'San Pablo Anzoátegui',false),
	 (2,'San Tomé',false),
	 (2,'Santa Ana de Anzoátegui',false),
	 (2,'Santa Fe Anzoátegui',false),
	 (2,'Santa Rosa',false),
	 (2,'Soledad',false),
	 (2,'Urica',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (2,'Valle de Guanape',false),
	 (3,'Achaguas',false),
	 (3,'Biruaca',false),
	 (3,'Bruzual',false),
	 (3,'El Amparo',false),
	 (3,'El Nula',false),
	 (3,'Elorza',false),
	 (3,'Guasdualito',false),
	 (3,'Mantecal',false),
	 (3,'Puerto Páez',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (3,'San Fernando de Apure',true),
	 (3,'San Juan de Payara',false),
	 (4,'Barbacoas',false),
	 (4,'Cagua',false),
	 (4,'Camatagua',false),
	 (4,'Choroní',false),
	 (4,'Colonia Tovar',false),
	 (4,'El Consejo',false),
	 (4,'La Victoria',false),
	 (4,'Las Tejerías',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (4,'Magdaleno',false),
	 (4,'Maracay',true),
	 (4,'Ocumare de La Costa',false),
	 (4,'Palo Negro',false),
	 (4,'San Casimiro',false),
	 (4,'San Mateo',false),
	 (4,'San Sebastián',false),
	 (4,'Santa Cruz de Aragua',false),
	 (4,'Tocorón',false),
	 (4,'Turmero',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (4,'Villa de Cura',false),
	 (4,'Zuata',false),
	 (5,'Barinas',true),
	 (5,'Barinitas',false),
	 (5,'Barrancas',false),
	 (5,'Calderas',false),
	 (5,'Capitanejo',false),
	 (5,'Ciudad Bolivia',false),
	 (5,'El Cantón',false),
	 (5,'Las Veguitas',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (5,'Libertad de Barinas',false),
	 (5,'Sabaneta',false),
	 (5,'Santa Bárbara de Barinas',false),
	 (5,'Socopó',false),
	 (6,'Caicara del Orinoco',false),
	 (6,'Canaima',false),
	 (6,'Ciudad Bolívar',true),
	 (6,'Ciudad Piar',false),
	 (6,'El Callao',false),
	 (6,'El Dorado',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (6,'El Manteco',false),
	 (6,'El Palmar',false),
	 (6,'El Pao',false),
	 (6,'Guasipati',false),
	 (6,'Guri',false),
	 (6,'La Paragua',false),
	 (6,'Matanzas',false),
	 (6,'Puerto Ordaz',false),
	 (6,'San Félix',false),
	 (6,'Santa Elena de Uairén',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (6,'Tumeremo',false),
	 (6,'Unare',false),
	 (6,'Upata',false),
	 (7,'Bejuma',false),
	 (7,'Belén',false),
	 (7,'Campo de Carabobo',false),
	 (7,'Canoabo',false),
	 (7,'Central Tacarigua',false),
	 (7,'Chirgua',false),
	 (7,'Ciudad Alianza',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (7,'El Palito',false),
	 (7,'Guacara',false),
	 (7,'Guigue',false),
	 (7,'Las Trincheras',false),
	 (7,'Los Guayos',false),
	 (7,'Mariara',false),
	 (7,'Miranda',false),
	 (7,'Montalbán',false),
	 (7,'Morón',false),
	 (7,'Naguanagua',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (7,'Puerto Cabello',false),
	 (7,'San Joaquín',false),
	 (7,'Tocuyito',false),
	 (7,'Urama',false),
	 (7,'Valencia',true),
	 (7,'Vigirimita',false),
	 (8,'Aguirre',false),
	 (8,'Apartaderos Cojedes',false),
	 (8,'Arismendi',false),
	 (8,'Camuriquito',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (8,'El Baúl',false),
	 (8,'El Limón',false),
	 (8,'El Pao Cojedes',false),
	 (8,'El Socorro',false),
	 (8,'La Aguadita',false),
	 (8,'Las Vegas',false),
	 (8,'Libertad de Cojedes',false),
	 (8,'Mapuey',false),
	 (8,'Piñedo',false),
	 (8,'Samancito',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (8,'San Carlos',true),
	 (8,'Sucre',false),
	 (8,'Tinaco',false),
	 (8,'Tinaquillo',false),
	 (8,'Vallecito',false),
	 (9,'Tucupita',true),
	 (24,'Caracas',true),
	 (24,'El Junquito',false),
	 (10,'Adícora',false),
	 (10,'Boca de Aroa',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (10,'Cabure',false),
	 (10,'Capadare',false),
	 (10,'Capatárida',false),
	 (10,'Chichiriviche',false),
	 (10,'Churuguara',false),
	 (10,'Coro',true),
	 (10,'Cumarebo',false),
	 (10,'Dabajuro',false),
	 (10,'Judibana',false),
	 (10,'La Cruz de Taratara',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (10,'La Vela de Coro',false),
	 (10,'Los Taques',false),
	 (10,'Maparari',false),
	 (10,'Mene de Mauroa',false),
	 (10,'Mirimire',false),
	 (10,'Pedregal',false),
	 (10,'Píritu Falcón',false),
	 (10,'Pueblo Nuevo Falcón',false),
	 (10,'Puerto Cumarebo',false),
	 (10,'Punta Cardón',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (10,'Punto Fijo',false),
	 (10,'San Juan de Los Cayos',false),
	 (10,'San Luis',false),
	 (10,'Santa Ana Falcón',false),
	 (10,'Santa Cruz De Bucaral',false),
	 (10,'Tocopero',false),
	 (10,'Tocuyo de La Costa',false),
	 (10,'Tucacas',false),
	 (10,'Yaracal',false),
	 (11,'Altagracia de Orituco',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (11,'Cabruta',false),
	 (11,'Calabozo',false),
	 (11,'Camaguán',false),
	 (11,'Chaguaramas Guárico',false),
	 (11,'El Socorro',false),
	 (11,'El Sombrero',false),
	 (11,'Las Mercedes de Los Llanos',false),
	 (11,'Lezama',false),
	 (11,'Onoto',false),
	 (11,'Ortíz',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (11,'San José de Guaribe',false),
	 (11,'San Juan de Los Morros',true),
	 (11,'San Rafael de Laya',false),
	 (11,'Santa María de Ipire',false),
	 (11,'Tucupido',false),
	 (11,'Valle de La Pascua',false),
	 (11,'Zaraza',false),
	 (12,'Aguada Grande',false),
	 (12,'Atarigua',false),
	 (12,'Barquisimeto',true);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (12,'Bobare',false),
	 (12,'Cabudare',false),
	 (12,'Carora',false),
	 (12,'Cubiro',false),
	 (12,'Cují',false),
	 (12,'Duaca',false),
	 (12,'El Manzano',false),
	 (12,'El Tocuyo',false),
	 (12,'Guaríco',false),
	 (12,'Humocaro Alto',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (12,'Humocaro Bajo',false),
	 (12,'La Miel',false),
	 (12,'Moroturo',false),
	 (12,'Quíbor',false),
	 (12,'Río Claro',false),
	 (12,'Sanare',false),
	 (12,'Santa Inés',false),
	 (12,'Sarare',false),
	 (12,'Siquisique',false),
	 (12,'Tintorero',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (13,'Apartaderos Mérida',false),
	 (13,'Arapuey',false),
	 (13,'Bailadores',false),
	 (13,'Caja Seca',false),
	 (13,'Canaguá',false),
	 (13,'Chachopo',false),
	 (13,'Chiguara',false),
	 (13,'Ejido',false),
	 (13,'El Vigía',false),
	 (13,'La Azulita',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (13,'La Playa',false),
	 (13,'Lagunillas Mérida',false),
	 (13,'Mérida',true),
	 (13,'Mesa de Bolívar',false),
	 (13,'Mucuchíes',false),
	 (13,'Mucujepe',false),
	 (13,'Mucuruba',false),
	 (13,'Nueva Bolivia',false),
	 (13,'Palmarito',false),
	 (13,'Pueblo Llano',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (13,'Santa Cruz de Mora',false),
	 (13,'Santa Elena de Arenales',false),
	 (13,'Santo Domingo',false),
	 (13,'Tabáy',false),
	 (13,'Timotes',false),
	 (13,'Torondoy',false),
	 (13,'Tovar',false),
	 (13,'Tucani',false),
	 (13,'Zea',false),
	 (14,'Araguita',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (14,'Carrizal',false),
	 (14,'Caucagua',false),
	 (14,'Chaguaramas Miranda',false),
	 (14,'Charallave',false),
	 (14,'Chirimena',false),
	 (14,'Chuspa',false),
	 (14,'Cúa',false),
	 (14,'Cupira',false),
	 (14,'Curiepe',false),
	 (14,'El Guapo',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (14,'El Jarillo',false),
	 (14,'Filas de Mariche',false),
	 (14,'Guarenas',false),
	 (14,'Guatire',false),
	 (14,'Higuerote',false),
	 (14,'Los Anaucos',false),
	 (14,'Los Teques',true),
	 (14,'Ocumare del Tuy',false),
	 (14,'Panaquire',false),
	 (14,'Paracotos',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (14,'Río Chico',false),
	 (14,'San Antonio de Los Altos',false),
	 (14,'San Diego de Los Altos',false),
	 (14,'San Fernando del Guapo',false),
	 (14,'San Francisco de Yare',false),
	 (14,'San José de Los Altos',false),
	 (14,'San José de Río Chico',false),
	 (14,'San Pedro de Los Altos',false),
	 (14,'Santa Lucía',false),
	 (14,'Santa Teresa',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (14,'Tacarigua de La Laguna',false),
	 (14,'Tacarigua de Mamporal',false),
	 (14,'Tácata',false),
	 (14,'Turumo',false),
	 (15,'Aguasay',false),
	 (15,'Aragua de Maturín',false),
	 (15,'Barrancas del Orinoco',false),
	 (15,'Caicara de Maturín',false),
	 (15,'Caripe',false),
	 (15,'Caripito',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (15,'Chaguaramal',false),
	 (15,'Chaguaramas Monagas',false),
	 (15,'El Furrial',false),
	 (15,'El Tejero',false),
	 (15,'Jusepín',false),
	 (15,'La Toscana',false),
	 (15,'Maturín',true),
	 (15,'Miraflores',false),
	 (15,'Punta de Mata',false),
	 (15,'Quiriquire',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (15,'San Antonio de Maturín',false),
	 (15,'San Vicente Monagas',false),
	 (15,'Santa Bárbara',false),
	 (15,'Temblador',false),
	 (15,'Teresen',false),
	 (15,'Uracoa',false),
	 (16,'Altagracia',false),
	 (16,'Boca de Pozo',false),
	 (16,'Boca de Río',false),
	 (16,'El Espinal',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (16,'El Valle del Espíritu Santo',false),
	 (16,'El Yaque',false),
	 (16,'Juangriego',false),
	 (16,'La Asunción',true),
	 (16,'La Guardia',false),
	 (16,'Pampatar',false),
	 (16,'Porlamar',false),
	 (16,'Puerto Fermín',false),
	 (16,'Punta de Piedras',false),
	 (16,'San Francisco de Macanao',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (16,'San Juan Bautista',false),
	 (16,'San Pedro de Coche',false),
	 (16,'Santa Ana de Nueva Esparta',false),
	 (16,'Villa Rosa',false),
	 (17,'Acarigua',false),
	 (17,'Agua Blanca',false),
	 (17,'Araure',false),
	 (17,'Biscucuy',false),
	 (17,'Boconoito',false),
	 (17,'Campo Elías',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (17,'Chabasquén',false),
	 (17,'Guanare',true),
	 (17,'Guanarito',false),
	 (17,'La Aparición',false),
	 (17,'La Misión',false),
	 (17,'Mesa de Cavacas',false),
	 (17,'Ospino',false),
	 (17,'Papelón',false),
	 (17,'Payara',false),
	 (17,'Pimpinela',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (17,'Píritu de Portuguesa',false),
	 (17,'San Rafael de Onoto',false),
	 (17,'Santa Rosalía',false),
	 (17,'Turén',false),
	 (18,'Altos de Sucre',false),
	 (18,'Araya',false),
	 (18,'Cariaco',false),
	 (18,'Carúpano',false),
	 (18,'Casanay',false),
	 (18,'Cumaná',true);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (18,'Cumanacoa',false),
	 (18,'El Morro Puerto Santo',false),
	 (18,'El Pilar',false),
	 (18,'El Poblado',false),
	 (18,'Guaca',false),
	 (18,'Guiria',false),
	 (18,'Irapa',false),
	 (18,'Manicuare',false),
	 (18,'Mariguitar',false),
	 (18,'Río Caribe',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (18,'San Antonio del Golfo',false),
	 (18,'San José de Aerocuar',false),
	 (18,'San Vicente de Sucre',false),
	 (18,'Santa Fe de Sucre',false),
	 (18,'Tunapuy',false),
	 (18,'Yaguaraparo',false),
	 (18,'Yoco',false),
	 (19,'Abejales',false),
	 (19,'Borota',false),
	 (19,'Bramon',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (19,'Capacho',false),
	 (19,'Colón',false),
	 (19,'Coloncito',false),
	 (19,'Cordero',false),
	 (19,'El Cobre',false),
	 (19,'El Pinal',false),
	 (19,'Independencia',false),
	 (19,'La Fría',false),
	 (19,'La Grita',false),
	 (19,'La Pedrera',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (19,'La Tendida',false),
	 (19,'Las Delicias',false),
	 (19,'Las Hernández',false),
	 (19,'Lobatera',false),
	 (19,'Michelena',false),
	 (19,'Palmira',false),
	 (19,'Pregonero',false),
	 (19,'Queniquea',false),
	 (19,'Rubio',false),
	 (19,'San Antonio del Tachira',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (19,'San Cristobal',true),
	 (19,'San José de Bolívar',false),
	 (19,'San Josecito',false),
	 (19,'San Pedro del Río',false),
	 (19,'Santa Ana Táchira',false),
	 (19,'Seboruco',false),
	 (19,'Táriba',false),
	 (19,'Umuquena',false),
	 (19,'Ureña',false),
	 (20,'Batatal',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (20,'Betijoque',false),
	 (20,'Boconó',false),
	 (20,'Carache',false),
	 (20,'Chejende',false),
	 (20,'Cuicas',false),
	 (20,'El Dividive',false),
	 (20,'El Jaguito',false),
	 (20,'Escuque',false),
	 (20,'Isnotú',false),
	 (20,'Jajó',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (20,'La Ceiba',false),
	 (20,'La Concepción de Trujllo',false),
	 (20,'La Mesa de Esnujaque',false),
	 (20,'La Puerta',false),
	 (20,'La Quebrada',false),
	 (20,'Mendoza Fría',false),
	 (20,'Meseta de Chimpire',false),
	 (20,'Monay',false),
	 (20,'Motatán',false),
	 (20,'Pampán',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (20,'Pampanito',false),
	 (20,'Sabana de Mendoza',false),
	 (20,'San Lázaro',false),
	 (20,'Santa Ana de Trujillo',false),
	 (20,'Tostós',false),
	 (20,'Trujillo',true),
	 (20,'Valera',false),
	 (21,'Carayaca',false),
	 (21,'Litoral',false),
	 (25,'Archipiélago Los Roques',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (22,'Aroa',false),
	 (22,'Boraure',false),
	 (22,'Campo Elías de Yaracuy',false),
	 (22,'Chivacoa',false),
	 (22,'Cocorote',false),
	 (22,'Farriar',false),
	 (22,'Guama',false),
	 (22,'Marín',false),
	 (22,'Nirgua',false),
	 (22,'Sabana de Parra',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (22,'Salom',false),
	 (22,'San Felipe',true),
	 (22,'San Pablo de Yaracuy',false),
	 (22,'Urachiche',false),
	 (22,'Yaritagua',false),
	 (22,'Yumare',false),
	 (23,'Bachaquero',false),
	 (23,'Bobures',false),
	 (23,'Cabimas',false),
	 (23,'Campo Concepción',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (23,'Campo Mara',false),
	 (23,'Campo Rojo',false),
	 (23,'Carrasquero',false),
	 (23,'Casigua',false),
	 (23,'Chiquinquirá',false),
	 (23,'Ciudad Ojeda',false),
	 (23,'El Batey',false),
	 (23,'El Carmelo',false),
	 (23,'El Chivo',false),
	 (23,'El Guayabo',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (23,'El Mene',false),
	 (23,'El Venado',false),
	 (23,'Encontrados',false),
	 (23,'Gibraltar',false),
	 (23,'Isla de Toas',false),
	 (23,'La Concepción del Zulia',false),
	 (23,'La Paz',false),
	 (23,'La Sierrita',false),
	 (23,'Lagunillas del Zulia',false),
	 (23,'Las Piedras de Perijá',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (23,'Los Cortijos',false),
	 (23,'Machiques',false),
	 (23,'Maracaibo',true),
	 (23,'Mene Grande',false),
	 (23,'Palmarejo',false),
	 (23,'Paraguaipoa',false),
	 (23,'Potrerito',false),
	 (23,'Pueblo Nuevo del Zulia',false),
	 (23,'Puertos de Altagracia',false),
	 (23,'Punta Gorda',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (23,'Sabaneta de Palma',false),
	 (23,'San Francisco',false),
	 (23,'San José de Perijá',false),
	 (23,'San Rafael del Moján',false),
	 (23,'San Timoteo',false),
	 (23,'Santa Bárbara Del Zulia',false),
	 (23,'Santa Cruz de Mara',false),
	 (23,'Santa Cruz del Zulia',false),
	 (23,'Santa Rita',false),
	 (23,'Sinamaica',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (23,'Tamare',false),
	 (23,'Tía Juana',false),
	 (23,'Villa del Rosario',false),
	 (21,'La Guaira',true),
	 (21,'Catia La Mar',false),
	 (21,'Macuto',false),
	 (21,'Naiguatá',false),
	 (25,'Archipiélago Los Monjes',false),
	 (25,'Isla La Tortuga y Cayos adyacentes',false),
	 (25,'Isla La Sola',false);
INSERT INTO public.city (state_id,city_name,capital) VALUES
	 (25,'Islas Los Testigos',false),
	 (25,'Islas Los Frailes',false),
	 (25,'Isla La Orchila',false),
	 (25,'Archipiélago Las Aves',false),
	 (25,'Isla de Aves',false),
	 (25,'Isla La Blanquilla',false),
	 (25,'Isla de Patos',false),
	 (25,'Islas Los Hermanos',false);
