INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (1,'Alto Orinoco'),
	 (1,'Huachamacare Acanaña'),
	 (1,'Marawaka Toky Shamanaña'),
	 (1,'Mavaka Mavaka'),
	 (1,'Sierra Parima Parimabé'),
	 (2,'Ucata Laja Lisa'),
	 (2,'Yapacana Macuruco'),
	 (2,'Caname Guarinuma'),
	 (3,'Fernando Girón Tovar'),
	 (3,'Luis Alberto Gómez');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (3,'Pahueña Limón de Parhueña'),
	 (3,'Platanillal Platanillal'),
	 (4,'Samariapo'),
	 (4,'Sipapo'),
	 (4,'Munduapo'),
	 (4,'Guayapo'),
	 (5,'Alto Ventuari'),
	 (5,'Medio Ventuari'),
	 (5,'Bajo Ventuari'),
	 (6,'Victorino');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (6,'Comunidad'),
	 (7,'Casiquiare'),
	 (7,'Cocuy'),
	 (7,'San Carlos de Río Negro'),
	 (7,'Solano'),
	 (8,'Anaco'),
	 (8,'San Joaquín'),
	 (9,'Cachipo'),
	 (9,'Aragua de Barcelona'),
	 (11,'Lechería');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (11,'El Morro'),
	 (12,'Puerto Píritu'),
	 (12,'San Miguel'),
	 (12,'Sucre'),
	 (13,'Valle de Guanape'),
	 (13,'Santa Bárbara'),
	 (14,'El Chaparro'),
	 (14,'Tomás Alfaro'),
	 (14,'Calatrava'),
	 (15,'Guanta');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (15,'Chorrerón'),
	 (16,'Mamo'),
	 (16,'Soledad'),
	 (17,'Mapire'),
	 (17,'Piar'),
	 (17,'Santa Clara'),
	 (17,'San Diego de Cabrutica'),
	 (17,'Uverito'),
	 (17,'Zuata'),
	 (18,'Puerto La Cruz');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (18,'Pozuelos'),
	 (19,'Onoto'),
	 (19,'San Pablo'),
	 (20,'San Mateo'),
	 (20,'El Carito'),
	 (20,'Santa Inés'),
	 (20,'La Romereña'),
	 (21,'Atapirire'),
	 (21,'Boca del Pao'),
	 (21,'El Pao');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (21,'Pariaguán'),
	 (22,'Cantaura'),
	 (22,'Libertador'),
	 (22,'Santa Rosa'),
	 (22,'Urica'),
	 (23,'Píritu'),
	 (23,'San Francisco'),
	 (24,'San José de Guanipa'),
	 (25,'Boca de Uchire'),
	 (25,'Boca de Chávez');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (26,'Pueblo Nuevo'),
	 (26,'Santa Ana'),
	 (27,'Bergantín'),
	 (27,'Caigua'),
	 (27,'El Carmen'),
	 (27,'El Pilar'),
	 (27,'Naricual'),
	 (27,'San Crsitóbal'),
	 (28,'Edmundo Barrios'),
	 (28,'Miguel Otero Silva');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (29,'Achaguas'),
	 (29,'Apurito'),
	 (29,'El Yagual'),
	 (29,'Guachara'),
	 (29,'Mucuritas'),
	 (29,'Queseras del medio'),
	 (30,'Biruaca'),
	 (31,'Bruzual'),
	 (31,'Mantecal'),
	 (31,'Quintero');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (31,'Rincón Hondo'),
	 (31,'San Vicente'),
	 (32,'Guasdualito'),
	 (32,'Aramendi'),
	 (32,'El Amparo'),
	 (32,'San Camilo'),
	 (32,'Urdaneta'),
	 (33,'San Juan de Payara'),
	 (33,'Codazzi'),
	 (33,'Cunaviche');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (34,'Elorza'),
	 (34,'La Trinidad'),
	 (35,'San Fernando'),
	 (35,'El Recreo'),
	 (35,'Peñalver'),
	 (35,'San Rafael de Atamaica'),
	 (36,'Pedro José Ovalles'),
	 (36,'Joaquín Crespo'),
	 (36,'José Casanova Godoy'),
	 (36,'Madre María de San José');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (36,'Andrés Eloy Blanco'),
	 (36,'Los Tacarigua'),
	 (36,'Las Delicias'),
	 (36,'Choroní'),
	 (37,'Bolívar'),
	 (38,'Camatagua'),
	 (38,'Carmen de Cura'),
	 (39,'Santa Rita'),
	 (39,'Francisco de Miranda'),
	 (39,'Moseñor Feliciano González');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (40,'Santa Cruz'),
	 (41,'José Félix Ribas'),
	 (41,'Castor Nieves Ríos'),
	 (41,'Las Guacamayas'),
	 (41,'Pao de Zárate'),
	 (41,'Zuata'),
	 (42,'José Rafael Revenga'),
	 (43,'Palo Negro'),
	 (43,'San Martín de Porres'),
	 (44,'El Limón');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (44,'Caña de Azúcar'),
	 (45,'Ocumare de la Costa'),
	 (46,'San Casimiro'),
	 (46,'Güiripa'),
	 (46,'Ollas de Caramacate'),
	 (46,'Valle Morín'),
	 (47,'San Sebastían'),
	 (48,'Turmero'),
	 (48,'Arevalo Aponte'),
	 (48,'Chuao');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (48,'Samán de Güere'),
	 (48,'Alfredo Pacheco Miranda'),
	 (49,'Santos Michelena'),
	 (49,'Tiara'),
	 (50,'Cagua'),
	 (50,'Bella Vista'),
	 (51,'Tovar'),
	 (52,'Urdaneta'),
	 (52,'Las Peñitas'),
	 (52,'San Francisco de Cara');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (52,'Taguay'),
	 (53,'Zamora'),
	 (53,'Magdaleno'),
	 (53,'San Francisco de Asís'),
	 (53,'Valles de Tucutunemo'),
	 (53,'Augusto Mijares'),
	 (54,'Sabaneta'),
	 (54,'Juan Antonio Rodríguez Domínguez'),
	 (55,'El Cantón'),
	 (55,'Santa Cruz de Guacas');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (55,'Puerto Vivas'),
	 (56,'Ticoporo'),
	 (56,'Nicolás Pulido'),
	 (56,'Andrés Bello'),
	 (57,'Arismendi'),
	 (57,'Guadarrama'),
	 (57,'La Unión'),
	 (57,'San Antonio'),
	 (58,'Barinas'),
	 (58,'Alberto Arvelo Larriva');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (58,'San Silvestre'),
	 (58,'Santa Inés'),
	 (58,'Santa Lucía'),
	 (58,'Torumos'),
	 (58,'El Carmen'),
	 (58,'Rómulo Betancourt'),
	 (58,'Corazón de Jesús'),
	 (58,'Ramón Ignacio Méndez'),
	 (58,'Alto Barinas'),
	 (58,'Manuel Palacio Fajardo');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (58,'Juan Antonio Rodríguez Domínguez'),
	 (58,'Dominga Ortiz de Páez'),
	 (59,'Barinitas'),
	 (59,'Altamira de Cáceres'),
	 (59,'Calderas'),
	 (60,'Barrancas'),
	 (60,'El Socorro'),
	 (60,'Mazparrito'),
	 (61,'Santa Bárbara'),
	 (61,'Pedro Briceño Méndez');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (61,'Ramón Ignacio Méndez'),
	 (61,'José Ignacio del Pumar'),
	 (62,'Obispos'),
	 (62,'Guasimitos'),
	 (62,'El Real'),
	 (62,'La Luz'),
	 (63,'Ciudad Bolívia'),
	 (63,'José Ignacio Briceño'),
	 (63,'José Félix Ribas'),
	 (63,'Páez');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (64,'Libertad'),
	 (64,'Dolores'),
	 (64,'Santa Rosa'),
	 (64,'Palacio Fajardo'),
	 (65,'Ciudad de Nutrias'),
	 (65,'El Regalo'),
	 (65,'Puerto Nutrias'),
	 (65,'Santa Catalina'),
	 (66,'Cachamay'),
	 (66,'Chirica');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (66,'Dalla Costa'),
	 (66,'Once de Abril'),
	 (66,'Simón Bolívar'),
	 (66,'Unare'),
	 (66,'Universidad'),
	 (66,'Vista al Sol'),
	 (66,'Pozo Verde'),
	 (66,'Yocoima'),
	 (66,'5 de Julio'),
	 (67,'Cedeño');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (67,'Altagracia'),
	 (67,'Ascensión Farreras'),
	 (67,'Guaniamo'),
	 (67,'La Urbana'),
	 (67,'Pijiguaos'),
	 (68,'El Callao'),
	 (69,'Gran Sabana'),
	 (69,'Ikabarú'),
	 (70,'Catedral'),
	 (70,'Zea');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (70,'Orinoco'),
	 (70,'José Antonio Páez'),
	 (70,'Marhuanta'),
	 (70,'Agua Salada'),
	 (70,'Vista Hermosa'),
	 (70,'La Sabanita'),
	 (70,'Panapana'),
	 (71,'Andrés Eloy Blanco'),
	 (71,'Pedro Cova'),
	 (72,'Raúl Leoni');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (72,'Barceloneta'),
	 (72,'Santa Bárbara'),
	 (72,'San Francisco'),
	 (73,'Roscio'),
	 (73,'Salóm'),
	 (74,'Sifontes'),
	 (74,'Dalla Costa'),
	 (74,'San Isidro'),
	 (75,'Sucre'),
	 (75,'Aripao');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (75,'Guarataro'),
	 (75,'Las Majadas'),
	 (75,'Moitaco'),
	 (76,'Padre Pedro Chien'),
	 (76,'Río Grande'),
	 (77,'Bejuma'),
	 (77,'Canoabo'),
	 (77,'Simón Bolívar'),
	 (78,'Güigüe'),
	 (78,'Carabobo');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (78,'Tacarigua'),
	 (79,'Mariara'),
	 (79,'Aguas Calientes'),
	 (80,'Ciudad Alianza'),
	 (80,'Guacara'),
	 (80,'Yagua'),
	 (81,'Morón'),
	 (81,'Yagua'),
	 (82,'Tocuyito'),
	 (82,'Independencia');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (83,'Los Guayos'),
	 (84,'Miranda'),
	 (85,'Montalbán'),
	 (86,'Naguanagua'),
	 (87,'Bartolomé Salóm'),
	 (87,'Democracia'),
	 (87,'Fraternidad'),
	 (87,'Goaigoaza'),
	 (87,'Juan José Flores'),
	 (87,'Unión');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (87,'Borburata'),
	 (87,'Patanemo'),
	 (88,'San Diego'),
	 (89,'San Joaquín'),
	 (90,'Candelaria'),
	 (90,'Catedral'),
	 (90,'El Socorro'),
	 (90,'Miguel Peña'),
	 (90,'Rafael Urdaneta'),
	 (90,'San Blas');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (90,'San José'),
	 (90,'Santa Rosa'),
	 (90,'Negro Primero'),
	 (91,'Cojedes'),
	 (91,'Juan de Mata Suárez'),
	 (92,'Tinaquillo'),
	 (93,'El Baúl'),
	 (93,'Sucre'),
	 (94,'La Aguadita'),
	 (94,'Macapo');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (95,'El Pao'),
	 (96,'El Amparo'),
	 (96,'Libertad de Cojedes'),
	 (97,'Rómulo Gallegos'),
	 (98,'San Carlos de Austria'),
	 (98,'Juan Ángel Bravo'),
	 (98,'Manuel Manrique'),
	 (99,'General en Jefe José Laurencio Silva'),
	 (100,'Curiapo'),
	 (100,'Almirante Luis Brión');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (100,'Francisco Aniceto Lugo'),
	 (100,'Manuel Renaud'),
	 (100,'Padre Barral'),
	 (100,'Santos de Abelgas'),
	 (101,'Imataca'),
	 (101,'Cinco de Julio'),
	 (101,'Juan Bautista Arismendi'),
	 (101,'Manuel Piar'),
	 (101,'Rómulo Gallegos'),
	 (102,'Pedernales');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (102,'Luis Beltrán Prieto Figueroa'),
	 (103,'San José (Delta Amacuro)'),
	 (103,'José Vidal Marcano'),
	 (103,'Juan Millán'),
	 (103,'Leonardo Ruíz Pineda'),
	 (103,'Mariscal Antonio José de Sucre'),
	 (103,'Monseñor Argimiro García'),
	 (103,'San Rafael (Delta Amacuro)'),
	 (103,'Virgen del Valle'),
	 (10,'Clarines');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (10,'Guanape'),
	 (10,'Sabana de Uchire'),
	 (104,'Capadare'),
	 (104,'La Pastora'),
	 (104,'Libertador'),
	 (104,'San Juan de los Cayos'),
	 (105,'Aracua'),
	 (105,'La Peña'),
	 (105,'San Luis'),
	 (106,'Bariro');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (106,'Borojó'),
	 (106,'Capatárida'),
	 (106,'Guajiro'),
	 (106,'Seque'),
	 (106,'Zazárida'),
	 (106,'Valle de Eroa'),
	 (107,'Cacique Manaure'),
	 (108,'Norte'),
	 (108,'Carirubana'),
	 (108,'Santa Ana');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (108,'Urbana Punta Cardón'),
	 (109,'La Vela de Coro'),
	 (109,'Acurigua'),
	 (109,'Guaibacoa'),
	 (109,'Las Calderas'),
	 (109,'Macoruca'),
	 (110,'Dabajuro'),
	 (111,'Agua Clara'),
	 (111,'Avaria'),
	 (111,'Pedregal');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (111,'Piedra Grande'),
	 (111,'Purureche'),
	 (112,'Adaure'),
	 (112,'Adícora'),
	 (112,'Baraived'),
	 (112,'Buena Vista'),
	 (112,'Jadacaquiva'),
	 (112,'El Vínculo'),
	 (112,'El Hato'),
	 (112,'Moruy');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (112,'Pueblo Nuevo'),
	 (113,'Agua Larga'),
	 (113,'El Paují'),
	 (113,'Independencia'),
	 (113,'Mapararí'),
	 (114,'Agua Linda'),
	 (114,'Araurima'),
	 (114,'Jacura'),
	 (115,'Tucacas'),
	 (115,'Boca de Aroa');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (116,'Los Taques'),
	 (116,'Judibana'),
	 (117,'Mene de Mauroa'),
	 (117,'San Félix'),
	 (117,'Casigua'),
	 (118,'Guzmán Guillermo'),
	 (118,'Mitare'),
	 (118,'Río Seco'),
	 (118,'Sabaneta'),
	 (118,'San Antonio');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (118,'San Gabriel'),
	 (118,'Santa Ana'),
	 (119,'Boca del Tocuyo'),
	 (119,'Chichiriviche'),
	 (119,'Tocuyo de la Costa'),
	 (120,'Palmasola'),
	 (121,'Cabure'),
	 (121,'Colina'),
	 (121,'Curimagua'),
	 (122,'San José de la Costa');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (122,'Píritu'),
	 (123,'San Francisco'),
	 (124,'Sucre'),
	 (124,'Pecaya'),
	 (125,'Tocópero'),
	 (126,'El Charal'),
	 (126,'Las Vegas del Tuy'),
	 (126,'Santa Cruz de Bucaral'),
	 (127,'Bruzual'),
	 (127,'Urumaco');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (128,'Puerto Cumarebo'),
	 (128,'La Ciénaga'),
	 (128,'La Soledad'),
	 (128,'Pueblo Cumarebo'),
	 (128,'Zazárida'),
	 (113,'Churuguara'),
	 (129,'Camaguán'),
	 (129,'Puerto Miranda'),
	 (129,'Uverito'),
	 (130,'Chaguaramas');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (131,'El Socorro'),
	 (132,'Tucupido'),
	 (132,'San Rafael de Laya'),
	 (133,'Altagracia de Orituco'),
	 (133,'San Rafael de Orituco'),
	 (133,'San Francisco Javier de Lezama'),
	 (133,'Paso Real de Macaira'),
	 (133,'Carlos Soublette'),
	 (133,'San Francisco de Macaira'),
	 (133,'Libertad de Orituco');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (134,'Cantaclaro'),
	 (134,'San Juan de los Morros'),
	 (134,'Parapara'),
	 (135,'El Sombrero'),
	 (135,'Sosa'),
	 (136,'Las Mercedes'),
	 (136,'Cabruta'),
	 (136,'Santa Rita de Manapire'),
	 (137,'Valle de la Pascua'),
	 (137,'Espino');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (138,'San José de Unare'),
	 (138,'Zaraza'),
	 (139,'San José de Tiznados'),
	 (139,'San Francisco de Tiznados'),
	 (139,'San Lorenzo de Tiznados'),
	 (139,'Ortiz'),
	 (140,'Guayabal'),
	 (140,'Cazorla'),
	 (141,'San José de Guaribe'),
	 (141,'Uveral');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (142,'Santa María de Ipire'),
	 (142,'Altamira'),
	 (143,'El Calvario'),
	 (143,'El Rastro'),
	 (143,'Guardatinajas'),
	 (143,'Capital Urbana Calabozo'),
	 (144,'Quebrada Honda de Guache'),
	 (144,'Pío Tamayo'),
	 (144,'Yacambú'),
	 (145,'Fréitez');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (145,'José María Blanco'),
	 (146,'Catedral'),
	 (146,'Concepción'),
	 (146,'El Cují'),
	 (146,'Juan de Villegas'),
	 (146,'Santa Rosa'),
	 (146,'Tamaca'),
	 (146,'Unión'),
	 (146,'Aguedo Felipe Alvarado'),
	 (146,'Buena Vista');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (146,'Juárez'),
	 (147,'Juan Bautista Rodríguez'),
	 (147,'Cuara'),
	 (147,'Diego de Lozada'),
	 (147,'Paraíso de San José'),
	 (147,'San Miguel'),
	 (147,'Tintorero'),
	 (147,'José Bernardo Dorante'),
	 (147,'Coronel Mariano Peraza '),
	 (148,'Bolívar');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (148,'Anzoátegui'),
	 (148,'Guarico'),
	 (148,'Hilario Luna y Luna'),
	 (148,'Humocaro Alto'),
	 (148,'Humocaro Bajo'),
	 (148,'La Candelaria'),
	 (148,'Morán'),
	 (149,'Cabudare'),
	 (149,'José Gregorio Bastidas'),
	 (149,'Agua Viva');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (150,'Sarare'),
	 (150,'Buría'),
	 (150,'Gustavo Vegas León'),
	 (151,'Trinidad Samuel'),
	 (151,'Antonio Díaz'),
	 (151,'Camacaro'),
	 (151,'Castañeda'),
	 (151,'Cecilio Zubillaga'),
	 (151,'Chiquinquirá'),
	 (151,'El Blanco');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (151,'Espinoza de los Monteros'),
	 (151,'Lara'),
	 (151,'Las Mercedes'),
	 (151,'Manuel Morillo'),
	 (151,'Montaña Verde'),
	 (151,'Montes de Oca'),
	 (151,'Torres'),
	 (151,'Heriberto Arroyo'),
	 (151,'Reyes Vargas'),
	 (151,'Altagracia');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (152,'Siquisique'),
	 (152,'Moroturo'),
	 (152,'San Miguel'),
	 (152,'Xaguas'),
	 (179,'Presidente Betancourt'),
	 (179,'Presidente Páez'),
	 (179,'Presidente Rómulo Gallegos'),
	 (179,'Gabriel Picón González'),
	 (179,'Héctor Amable Mora'),
	 (179,'José Nucete Sardi');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (179,'Pulido Méndez'),
	 (180,'La Azulita'),
	 (181,'Santa Cruz de Mora'),
	 (181,'Mesa Bolívar'),
	 (181,'Mesa de Las Palmas'),
	 (182,'Aricagua'),
	 (182,'San Antonio'),
	 (183,'Canagua'),
	 (183,'Capurí'),
	 (183,'Chacantá');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (183,'El Molino'),
	 (183,'Guaimaral'),
	 (183,'Mucutuy'),
	 (183,'Mucuchachí'),
	 (184,'Fernández Peña'),
	 (184,'Matriz'),
	 (184,'Montalbán'),
	 (184,'Acequias'),
	 (184,'Jají'),
	 (184,'La Mesa');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (184,'San José del Sur'),
	 (185,'Tucaní'),
	 (185,'Florencio Ramírez'),
	 (186,'Santo Domingo'),
	 (186,'Las Piedras'),
	 (187,'Guaraque'),
	 (187,'Mesa de Quintero'),
	 (187,'Río Negro'),
	 (188,'Arapuey'),
	 (188,'Palmira');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (189,'San Cristóbal de Torondoy'),
	 (189,'Torondoy'),
	 (190,'Antonio Spinetti Dini'),
	 (190,'Arias'),
	 (190,'Caracciolo Parra Pérez'),
	 (190,'Domingo Peña'),
	 (190,'El Llano'),
	 (190,'Gonzalo Picón Febres'),
	 (190,'Jacinto Plaza'),
	 (190,'Juan Rodríguez Suárez');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (190,'Lasso de la Vega'),
	 (190,'Mariano Picón Salas'),
	 (190,'Milla'),
	 (190,'Osuna Rodríguez'),
	 (190,'Sagrario'),
	 (190,'El Morro'),
	 (190,'Los Nevados'),
	 (191,'Andrés Eloy Blanco'),
	 (191,'La Venta'),
	 (191,'Piñango');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (191,'Timotes'),
	 (192,'Eloy Paredes'),
	 (192,'San Rafael de Alcázar'),
	 (192,'Santa Elena de Arenales'),
	 (193,'Santa María de Caparo'),
	 (194,'Pueblo Llano'),
	 (195,'Cacute'),
	 (195,'La Toma'),
	 (195,'Mucuchíes'),
	 (195,'Mucurubá');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (195,'San Rafael'),
	 (196,'Gerónimo Maldonado'),
	 (196,'Bailadores'),
	 (197,'Tabay'),
	 (198,'Chiguará'),
	 (198,'Estánquez'),
	 (198,'Lagunillas'),
	 (198,'La Trampa'),
	 (198,'Pueblo Nuevo del Sur'),
	 (198,'San Juan');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (199,'El Amparo'),
	 (199,'El Llano'),
	 (199,'San Francisco'),
	 (199,'Tovar'),
	 (200,'Independencia'),
	 (200,'María de la Concepción Palacios Blanco'),
	 (200,'Nueva Bolivia'),
	 (200,'Santa Apolonia'),
	 (201,'Caño El Tigre'),
	 (201,'Zea');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (223,'Aragüita'),
	 (223,'Arévalo González'),
	 (223,'Capaya'),
	 (223,'Caucagua'),
	 (223,'Panaquire'),
	 (223,'Ribas'),
	 (223,'El Café'),
	 (223,'Marizapa'),
	 (224,'Cumbo'),
	 (224,'San José de Barlovento');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (225,'El Cafetal'),
	 (225,'Las Minas'),
	 (225,'Nuestra Señora del Rosario'),
	 (226,'Higuerote'),
	 (226,'Curiepe'),
	 (226,'Tacarigua de Brión'),
	 (227,'Mamporal'),
	 (228,'Carrizal'),
	 (229,'Chacao'),
	 (230,'Charallave');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (230,'Las Brisas'),
	 (231,'El Hatillo'),
	 (232,'Altagracia de la Montaña'),
	 (232,'Cecilio Acosta'),
	 (232,'Los Teques'),
	 (232,'El Jarillo'),
	 (232,'San Pedro'),
	 (232,'Tácata'),
	 (232,'Paracotos'),
	 (233,'Cartanal');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (233,'Santa Teresa del Tuy'),
	 (234,'La Democracia'),
	 (234,'Ocumare del Tuy'),
	 (234,'Santa Bárbara'),
	 (235,'San Antonio de los Altos'),
	 (236,'Río Chico'),
	 (236,'El Guapo'),
	 (236,'Tacarigua de la Laguna'),
	 (236,'Paparo'),
	 (236,'San Fernando del Guapo');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (237,'Santa Lucía del Tuy'),
	 (238,'Cúpira'),
	 (238,'Machurucuto'),
	 (239,'Guarenas'),
	 (240,'San Antonio de Yare'),
	 (240,'San Francisco de Yare'),
	 (241,'Leoncio Martínez'),
	 (241,'Petare'),
	 (241,'Caucagüita'),
	 (241,'Filas de Mariche');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (241,'La Dolorita'),
	 (242,'Cúa'),
	 (242,'Nueva Cúa'),
	 (243,'Guatire'),
	 (243,'Bolívar'),
	 (258,'San Antonio de Maturín'),
	 (258,'San Francisco de Maturín'),
	 (259,'Aguasay'),
	 (260,'Caripito'),
	 (261,'El Guácharo');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (261,'La Guanota'),
	 (261,'Sabana de Piedra'),
	 (261,'San Agustín'),
	 (261,'Teresen'),
	 (261,'Caripe'),
	 (262,'Areo'),
	 (262,'Capital Cedeño'),
	 (262,'San Félix de Cantalicio'),
	 (262,'Viento Fresco'),
	 (263,'El Tejero');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (263,'Punta de Mata'),
	 (264,'Chaguaramas'),
	 (264,'Las Alhuacas'),
	 (264,'Tabasca'),
	 (264,'Temblador'),
	 (265,'Alto de los Godos'),
	 (265,'Boquerón'),
	 (265,'Las Cocuizas'),
	 (265,'La Cruz'),
	 (265,'San Simón');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (265,'El Corozo'),
	 (265,'El Furrial'),
	 (265,'Jusepín'),
	 (265,'La Pica'),
	 (265,'San Vicente'),
	 (266,'Aparicio'),
	 (266,'Aragua de Maturín'),
	 (266,'Chaguamal'),
	 (266,'El Pinto'),
	 (266,'Guanaguana');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (266,'La Toscana'),
	 (266,'Taguaya'),
	 (267,'Cachipo'),
	 (267,'Quiriquire'),
	 (268,'Santa Bárbara'),
	 (269,'Barrancas'),
	 (269,'Los Barrancos de Fajardo'),
	 (270,'Uracoa'),
	 (271,'Antolín del Campo'),
	 (272,'Arismendi');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (273,'García'),
	 (273,'Francisco Fajardo'),
	 (274,'Bolívar'),
	 (274,'Guevara'),
	 (274,'Matasiete'),
	 (274,'Santa Ana'),
	 (274,'Sucre'),
	 (275,'Aguirre'),
	 (275,'Maneiro'),
	 (276,'Adrián');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (276,'Juan Griego'),
	 (276,'Yaguaraparo'),
	 (277,'Porlamar'),
	 (278,'San Francisco de Macanao'),
	 (278,'Boca de Río'),
	 (279,'Tubores'),
	 (279,'Los Baleales'),
	 (280,'Vicente Fuentes'),
	 (280,'Villalba'),
	 (281,'San Juan Bautista');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (281,'Zabala'),
	 (283,'Capital Araure'),
	 (283,'Río Acarigua'),
	 (284,'Capital Esteller'),
	 (284,'Uveral'),
	 (285,'Guanare'),
	 (285,'Córdoba'),
	 (285,'San José de la Montaña'),
	 (285,'San Juan de Guanaguanare'),
	 (285,'Virgen de la Coromoto');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (286,'Guanarito'),
	 (286,'Trinidad de la Capilla'),
	 (286,'Divina Pastora'),
	 (287,'Monseñor José Vicente de Unda'),
	 (287,'Peña Blanca'),
	 (288,'Capital Ospino'),
	 (288,'Aparición'),
	 (288,'La Estación'),
	 (289,'Páez'),
	 (289,'Payara');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (289,'Pimpinela'),
	 (289,'Ramón Peraza'),
	 (290,'Papelón'),
	 (290,'Caño Delgadito'),
	 (291,'San Genaro de Boconoito'),
	 (291,'Antolín Tovar'),
	 (292,'San Rafael de Onoto'),
	 (292,'Santa Fe'),
	 (292,'Thermo Morles'),
	 (293,'Santa Rosalía');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (293,'Florida'),
	 (294,'Sucre'),
	 (294,'Concepción'),
	 (294,'San Rafael de Palo Alzado'),
	 (294,'Uvencio Antonio Velásquez'),
	 (294,'San José de Saguaz'),
	 (294,'Villa Rosa'),
	 (295,'Turén'),
	 (295,'Canelones'),
	 (295,'Santa Cruz');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (295,'San Isidro Labrador'),
	 (296,'Mariño'),
	 (296,'Rómulo Gallegos'),
	 (297,'San José de Aerocuar'),
	 (297,'Tavera Acosta'),
	 (298,'Río Caribe'),
	 (298,'Antonio José de Sucre'),
	 (298,'El Morro de Puerto Santo'),
	 (298,'Puerto Santo'),
	 (298,'San Juan de las Galdonas');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (299,'El Pilar'),
	 (299,'El Rincón'),
	 (299,'General Francisco Antonio Váquez'),
	 (299,'Guaraúnos'),
	 (299,'Tunapuicito'),
	 (299,'Unión'),
	 (300,'Santa Catalina'),
	 (300,'Santa Rosa'),
	 (300,'Santa Teresa'),
	 (300,'Bolívar');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (300,'Maracapana'),
	 (302,'Libertad'),
	 (302,'El Paujil'),
	 (302,'Yaguaraparo'),
	 (303,'Cruz Salmerón Acosta'),
	 (303,'Chacopata'),
	 (303,'Manicuare'),
	 (304,'Tunapuy'),
	 (304,'Campo Elías'),
	 (305,'Irapa');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (305,'Campo Claro'),
	 (305,'Maraval'),
	 (305,'San Antonio de Irapa'),
	 (305,'Soro'),
	 (306,'Mejía'),
	 (307,'Cumanacoa'),
	 (307,'Arenas'),
	 (307,'Aricagua'),
	 (307,'Cogollar'),
	 (307,'San Fernando');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (307,'San Lorenzo'),
	 (308,'Villa Frontado (Muelle de Cariaco)'),
	 (308,'Catuaro'),
	 (308,'Rendón'),
	 (308,'San Cruz'),
	 (308,'Santa María'),
	 (309,'Altagracia'),
	 (309,'Santa Inés'),
	 (309,'Valentín Valiente'),
	 (309,'Ayacucho');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (309,'San Juan'),
	 (309,'Raúl Leoni'),
	 (309,'Gran Mariscal'),
	 (310,'Cristóbal Colón'),
	 (310,'Bideau'),
	 (310,'Punta de Piedras'),
	 (310,'Güiria'),
	 (341,'Andrés Bello'),
	 (342,'Antonio Rómulo Costa'),
	 (343,'Ayacucho');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (343,'Rivas Berti'),
	 (343,'San Pedro del Río'),
	 (344,'Bolívar'),
	 (344,'Palotal'),
	 (344,'General Juan Vicente Gómez'),
	 (344,'Isaías Medina Angarita'),
	 (345,'Cárdenas'),
	 (345,'Amenodoro Ángel Lamus'),
	 (345,'La Florida'),
	 (346,'Córdoba');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (347,'Fernández Feo'),
	 (347,'Alberto Adriani'),
	 (347,'Santo Domingo'),
	 (348,'Francisco de Miranda'),
	 (349,'García de Hevia'),
	 (349,'Boca de Grita'),
	 (349,'José Antonio Páez'),
	 (350,'Guásimos'),
	 (351,'Independencia'),
	 (351,'Juan Germán Roscio');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (351,'Román Cárdenas'),
	 (352,'Jáuregui'),
	 (352,'Emilio Constantino Guerrero'),
	 (352,'Monseñor Miguel Antonio Salas'),
	 (353,'José María Vargas'),
	 (354,'Junín'),
	 (354,'La Petrólea'),
	 (354,'Quinimarí'),
	 (354,'Bramón'),
	 (355,'Libertad');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (355,'Cipriano Castro'),
	 (355,'Manuel Felipe Rugeles'),
	 (356,'Libertador'),
	 (356,'Doradas'),
	 (356,'Emeterio Ochoa'),
	 (356,'San Joaquín de Navay'),
	 (357,'Lobatera'),
	 (357,'Constitución'),
	 (358,'Michelena'),
	 (359,'Panamericano');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (359,'La Palmita'),
	 (360,'Pedro María Ureña'),
	 (360,'Nueva Arcadia'),
	 (361,'Delicias'),
	 (361,'Pecaya'),
	 (362,'Samuel Darío Maldonado'),
	 (362,'Boconó'),
	 (362,'Hernández'),
	 (363,'La Concordia'),
	 (363,'San Juan Bautista');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (363,'Pedro María Morantes'),
	 (363,'San Sebastián'),
	 (363,'Dr. Francisco Romero Lobo'),
	 (364,'Seboruco'),
	 (365,'Simón Rodríguez'),
	 (366,'Sucre'),
	 (366,'Eleazar López Contreras'),
	 (366,'San Pablo'),
	 (367,'Torbes'),
	 (368,'Uribante');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (368,'Cárdenas'),
	 (368,'Juan Pablo Peñalosa'),
	 (368,'Potosí'),
	 (369,'San Judas Tadeo'),
	 (370,'Araguaney'),
	 (370,'El Jaguito'),
	 (370,'La Esperanza'),
	 (370,'Santa Isabel'),
	 (371,'Boconó'),
	 (371,'El Carmen');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (371,'Mosquey'),
	 (371,'Ayacucho'),
	 (371,'Burbusay'),
	 (371,'General Ribas'),
	 (371,'Guaramacal'),
	 (371,'Vega de Guaramacal'),
	 (371,'Monseñor Jáuregui'),
	 (371,'Rafael Rangel'),
	 (371,'San Miguel'),
	 (371,'San José');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (372,'Sabana Grande'),
	 (372,'Cheregüé'),
	 (372,'Granados'),
	 (373,'Arnoldo Gabaldón'),
	 (373,'Bolivia'),
	 (373,'Carrillo'),
	 (373,'Cegarra'),
	 (373,'Chejendé'),
	 (373,'Manuel Salvador Ulloa'),
	 (373,'San José');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (374,'Carache'),
	 (374,'La Concepción'),
	 (374,'Cuicas'),
	 (374,'Panamericana'),
	 (374,'Santa Cruz'),
	 (375,'Escuque'),
	 (375,'La Unión'),
	 (375,'Santa Rita'),
	 (375,'Sabana Libre'),
	 (376,'El Socorro');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (376,'Los Caprichos'),
	 (376,'Antonio José de Sucre'),
	 (377,'Campo Elías'),
	 (377,'Arnoldo Gabaldón'),
	 (378,'Santa Apolonia'),
	 (378,'El Progreso'),
	 (378,'La Ceiba'),
	 (378,'Tres de Febrero'),
	 (379,'El Dividive'),
	 (379,'Agua Santa');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (379,'Agua Caliente'),
	 (379,'El Cenizo'),
	 (379,'Valerita'),
	 (380,'Monte Carmelo'),
	 (380,'Buena Vista'),
	 (380,'Santa María del Horcón'),
	 (381,'Motatán'),
	 (381,'El Baño'),
	 (381,'Jalisco'),
	 (382,'Pampán');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (382,'Flor de Patria'),
	 (382,'La Paz'),
	 (382,'Santa Ana'),
	 (383,'Pampanito'),
	 (383,'La Concepción'),
	 (383,'Pampanito II'),
	 (384,'Betijoque'),
	 (384,'José Gregorio Hernández'),
	 (384,'La Pueblita'),
	 (384,'Los Cedros');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (385,'Carvajal'),
	 (385,'Campo Alegre'),
	 (385,'Antonio Nicolás Briceño'),
	 (385,'José Leonardo Suárez'),
	 (386,'Sabana de Mendoza'),
	 (386,'Junín'),
	 (386,'Valmore Rodríguez'),
	 (386,'El Paraíso'),
	 (387,'Andrés Linares'),
	 (387,'Chiquinquirá');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (387,'Cristóbal Mendoza'),
	 (387,'Cruz Carrillo'),
	 (387,'Matriz'),
	 (387,'Monseñor Carrillo'),
	 (387,'Tres Esquinas'),
	 (388,'Cabimbú'),
	 (388,'Jajó'),
	 (388,'La Mesa de Esnujaque'),
	 (388,'Santiago'),
	 (388,'Tuñame');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (388,'La Quebrada'),
	 (389,'Juan Ignacio Montilla'),
	 (389,'La Beatriz'),
	 (389,'La Puerta'),
	 (389,'Mendoza del Valle de Momboy'),
	 (389,'Mercedes Díaz'),
	 (389,'San Luis'),
	 (390,'Caraballeda'),
	 (390,'Carayaca'),
	 (390,'Carlos Soublette');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (390,'Caruao Chuspa'),
	 (390,'Catia La Mar'),
	 (390,'El Junko'),
	 (390,'La Guaira'),
	 (390,'Macuto'),
	 (390,'Maiquetía'),
	 (390,'Naiguatá'),
	 (390,'Urimare'),
	 (391,'Arístides Bastidas'),
	 (392,'Bolívar');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (407,'Chivacoa'),
	 (407,'Campo Elías'),
	 (408,'Cocorote'),
	 (409,'Independencia'),
	 (410,'José Antonio Páez'),
	 (411,'La Trinidad'),
	 (412,'Manuel Monge'),
	 (413,'Salóm'),
	 (413,'Temerla'),
	 (413,'Nirgua');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (414,'San Andrés'),
	 (414,'Yaritagua'),
	 (415,'San Javier'),
	 (415,'Albarico'),
	 (415,'San Felipe'),
	 (416,'Sucre'),
	 (417,'Urachiche'),
	 (418,'El Guayabo'),
	 (418,'Farriar'),
	 (441,'Isla de Toas');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (441,'Monagas'),
	 (442,'San Timoteo'),
	 (442,'General Urdaneta'),
	 (442,'Libertador'),
	 (442,'Marcelino Briceño'),
	 (442,'Pueblo Nuevo'),
	 (442,'Manuel Guanipa Matos'),
	 (443,'Ambrosio'),
	 (443,'Carmen Herrera'),
	 (443,'La Rosa');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (443,'Germán Ríos Linares'),
	 (443,'San Benito'),
	 (443,'Rómulo Betancourt'),
	 (443,'Jorge Hernández'),
	 (443,'Punta Gorda'),
	 (443,'Arístides Calvani'),
	 (444,'Encontrados'),
	 (444,'Udón Pérez'),
	 (445,'Moralito'),
	 (445,'San Carlos del Zulia');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (445,'Santa Cruz del Zulia'),
	 (445,'Santa Bárbara'),
	 (445,'Urribarrí'),
	 (446,'Carlos Quevedo'),
	 (446,'Francisco Javier Pulgar'),
	 (446,'Simón Rodríguez'),
	 (446,'Guamo-Gavilanes'),
	 (448,'La Concepción'),
	 (448,'San José'),
	 (448,'Mariano Parra León');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (448,'José Ramón Yépez'),
	 (449,'Jesús María Semprún'),
	 (449,'Barí'),
	 (450,'Concepción'),
	 (450,'Andrés Bello'),
	 (450,'Chiquinquirá'),
	 (450,'El Carmelo'),
	 (450,'Potreritos'),
	 (451,'Libertad'),
	 (451,'Alonso de Ojeda');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (451,'Venezuela'),
	 (451,'Eleazar López Contreras'),
	 (451,'Campo Lara'),
	 (452,'Bartolomé de las Casas'),
	 (452,'Libertad'),
	 (452,'Río Negro'),
	 (452,'San José de Perijá'),
	 (453,'San Rafael'),
	 (453,'La Sierrita'),
	 (453,'Las Parcelas');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (453,'Luis de Vicente'),
	 (453,'Monseñor Marcos Sergio Godoy'),
	 (453,'Ricaurte'),
	 (453,'Tamare'),
	 (454,'Antonio Borjas Romero'),
	 (454,'Bolívar'),
	 (454,'Cacique Mara'),
	 (454,'Carracciolo Parra Pérez'),
	 (454,'Cecilio Acosta'),
	 (454,'Cristo de Aranza');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (454,'Coquivacoa'),
	 (454,'Chiquinquirá'),
	 (454,'Francisco Eugenio Bustamante'),
	 (454,'Idelfonzo Vásquez'),
	 (454,'Juana de Ávila'),
	 (454,'Luis Hurtado Higuera'),
	 (454,'Manuel Dagnino'),
	 (454,'Olegario Villalobos'),
	 (454,'Raúl Leoni'),
	 (454,'Santa Lucía');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (454,'Venancio Pulgar'),
	 (454,'San Isidro'),
	 (455,'Altagracia'),
	 (455,'Faría'),
	 (455,'Ana María Campos'),
	 (455,'San Antonio'),
	 (455,'San José'),
	 (456,'Donaldo García'),
	 (456,'El Rosario'),
	 (456,'Sixto Zambrano');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (457,'San Francisco'),
	 (457,'El Bajo'),
	 (457,'Domitila Flores'),
	 (457,'Francisco Ochoa'),
	 (457,'Los Cortijos'),
	 (457,'Marcial Hernández'),
	 (458,'Santa Rita'),
	 (458,'El Mene'),
	 (458,'Pedro Lucas Urribarrí'),
	 (458,'José Cenobio Urribarrí');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (459,'Rafael Maria Baralt'),
	 (459,'Manuel Manrique'),
	 (459,'Rafael Urdaneta'),
	 (460,'Bobures'),
	 (460,'Gibraltar'),
	 (460,'Heras'),
	 (460,'Monseñor Arturo Álvarez'),
	 (460,'Rómulo Gallegos'),
	 (460,'El Batey'),
	 (461,'Rafael Urdaneta');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (461,'La Victoria'),
	 (461,'Raúl Cuenca'),
	 (447,'Sinamaica'),
	 (447,'Alta Guajira'),
	 (447,'Elías Sánchez Rubio'),
	 (447,'Guajira'),
	 (462,'Altagracia'),
	 (462,'Antímano'),
	 (462,'Caricuao'),
	 (462,'Catedral');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (462,'Coche'),
	 (462,'El Junquito'),
	 (462,'El Paraíso'),
	 (462,'El Recreo'),
	 (462,'El Valle'),
	 (462,'La Candelaria'),
	 (462,'La Pastora'),
	 (462,'La Vega'),
	 (462,'Macarao'),
	 (462,'San Agustín');
INSERT INTO public.parish (municipality_id,parish_name) VALUES
	 (462,'San Bernardino'),
	 (462,'San José'),
	 (462,'San Juan'),
	 (462,'San Pedro'),
	 (462,'Santa Rosalía'),
	 (462,'Santa Teresa'),
	 (462,'Sucre (Catia)'),
	 (462,'23 de enero');
